#
#	Makefile for master includes
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

import:
	for f in $(BLD_INC_DIR)/*slots* ; do \
		echo cp $$f . ; \
		chmod +w *.h ; \
		cp $$f . ; \
	done

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
