#
#	Makefile for master includes
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

import:
	for f in $(BLD_INC_DIR)/*slots* ; do \
		echo cp $$f . ; \
		cp $$f . ; \
	done
