/*
    bit.h -- Build It Configuration Header for windows-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT_AUTH "file"
#define BIT_BUILD_NUMBER "0"
#define BIT_COMPANY "Embedthis"
#define BIT_DEPTH 1
#define BIT_DIGEST 1
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 0
#define BIT_HAS_MMU 1
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_HTTP_PORT 80
#define BIT_MANAGER "appman"
#define BIT_MDB 1
#define BIT_MINIMAL "doxygen,dsi,ejs,man,man2html,pmaker,ssl,ejscript,php,matrixssl,openssl"
#define BIT_OPTIONAL "cgi,dir,doxygen,dsi,ejs,ejscript,esp,man,man2html,openssl,matrixssl,pmaker,php,sqlite,ssl,utest,zip"
#define BIT_PACKS "bits/packs"
#define BIT_PAM 1
#define BIT_PLATFORMS "local"
#define BIT_PRODUCT "appweb"
#define BIT_REQUIRED "winsdk,compiler,link,dumpbin,rc,pcre"
#define BIT_SDB 0
#define BIT_SESSIONS 1
#define BIT_SSL_PORT 443
#define BIT_SYNC "http,mpr,pcre,sqlite"
#define BIT_TITLE "Embedthis Appweb"
#define BIT_VERSION "4.1.0"

/* Prefixes */
#define BIT_CFG_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BIT_BIN_PREFIX "C:/Program Files (x86)/Embedthis Appweb/bin"
#define BIT_INC_PREFIX "C:/Program Files (x86)/Embedthis Appweb/inc"
#define BIT_LOG_PREFIX "C:/Program Files (x86)/Embedthis Appweb/logs"
#define BIT_PRD_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BIT_SPL_PREFIX "C:/Program Files (x86)/Embedthis Appweb/tmp"
#define BIT_SRC_PREFIX "C:/Program Files (x86)/Embedthis Appweb/src"
#define BIT_VER_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BIT_WEB_PREFIX "C:/Program Files (x86)/Embedthis Appweb/web"

/* Suffixes */
#define BIT_EXE ".exe"
#define BIT_SHLIB ".lib"
#define BIT_SHOBJ ".dll"
#define BIT_LIB ".a"
#define BIT_OBJ ".obj"

/* Profile */
#define BIT_APPWEB_PRODUCT 1
#define BIT_PROFILE "vs"
#define BIT_CONFIG_CMD "bit -d -q -platform windows-x86 -without all -profile vs -configure . -gen vs"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 4
#define BIT_MINOR_VERSION 1
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 400010000

/* Packs */
#define BIT_PACK_CGI 1
#define BIT_PACK_CC 1
#define BIT_PACK_DIR 1
#define BIT_PACK_DOXYGEN 0
#define BIT_PACK_DSI 0
#define BIT_PACK_DUMPBIN 0
#define BIT_PACK_EJS 0
#define BIT_PACK_EJSCRIPT 0
#define BIT_PACK_ESP 1
#define BIT_PACK_HTTP 1
#define BIT_PACK_LINK 1
#define BIT_PACK_MAN 0
#define BIT_PACK_MAN2HTML 0
#define BIT_PACK_MATRIXSSL 0
#define BIT_PACK_OPENSSL 0
#define BIT_PACK_PCRE 1
#define BIT_PACK_PHP 0
#define BIT_PACK_PMAKER 0
#define BIT_PACK_RC 1
#define BIT_PACK_SQLITE 1
#define BIT_PACK_SSL 0
#define BIT_PACK_UTEST 1
#define BIT_PACK_WINSDK 1
#define BIT_PACK_ZIP 1
