/*
    bit.h -- Build It Configuration Header for win-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BLD_PRODUCT "appweb"
#define BLD_NAME "Embedthis Appweb"
#define BLD_COMPANY "Embedthis"
#define BLD_APPWEB_PRODUCT 1
#define BLD_VERSION "4.0.0"
#define BLD_NUMBER "B2"
#define BLD_MAJOR_VERSION 4
#define BLD_MINOR_VERSION 0
#define BLD_PATCH_VERSION 0
#define BLD_VNUM 400000000
#define BLD_CONFIG_CMD "bit -emulate win-x86 -q -d -without all configure -gen sh,nmake,vs"
#define BLD_LIB_NAME "bin"
#define BLD_CFG "win-x86-debug"
#define BLD_CFG_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BLD_BIN_PREFIX "C:/Program Files (x86)/Embedthis Appweb/bin"
#define BLD_DOC_PREFIX "C:/Program Files (x86)/Embedthis Appweb/doc"
#define BLD_INC_PREFIX "C:/Program Files (x86)/Embedthis Appweb/inc"
#define BLD_JEM_PREFIX "C:/Program Files (x86)/Embedthis Appweb/jems"
#define BLD_LIB_PREFIX "C:/Program Files (x86)/Embedthis Appweb/bin"
#define BLD_LOG_PREFIX "C:/Program Files (x86)/Embedthis Appweb/logs"
#define BLD_MAN_PREFIX "C:/Program Files (x86)/Embedthis Appweb/man"
#define BLD_PRD_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BLD_SAM_PREFIX "C:/Program Files (x86)/Embedthis Appweb/samples"
#define BLD_SPL_PREFIX "C:/Program Files (x86)/Embedthis Appweb/tmp"
#define BLD_SRC_PREFIX "C:/Program Files (x86)/Embedthis Appweb/src"
#define BLD_VER_PREFIX "C:/Program Files (x86)/Embedthis Appweb"
#define BLD_WEB_PREFIX "C:/Program Files (x86)/Embedthis Appweb/web"
#define BLD_EXE ".exe"
#define BLD_SHLIB ".lib"
#define BLD_SHOBJ ".dll"
#define BLD_LIB ".a"
#define BLD_OBJ ".obj"
#define BLD_FEATURE_AUTH_FILE 1
#define BLD_FEATURE_AUTH_PAM 0
#define BLD_FEATURE_MDB 1
#define BLD_FEATURE_SDB 0
#define BLD_MANAGER "appman"
#define BLD_CC_DOUBLE_BRACES 0
#define BLD_CC_DYN_LOAD 1
#define BLD_CC_EDITLINE 0
#define BLD_CC_MMU 1
#define BLD_CC_MTUNE 0
#define BLD_CC_PAM 0
#define BLD_CC_STACK_PROTECTOR 0
#define BLD_CC_SYNC 0
#define BLD_CC_SYNC_CAS 0
#define BLD_CC_UNNAMED_UNIONS 1
#define BLD_CC_WARN_64TO32 0
#define BLD_CC_WARN_UNUSED 0
#define BLD_FEATURE_HTTP 0
#define BLD_FEATURE_DOXYGEN 0
#define BLD_FEATURE_DSI 0
#define BLD_FEATURE_EJS 0
#define BLD_FEATURE_MAN 0
#define BLD_FEATURE_MAN2HTML 0
#define BLD_FEATURE_PHP 0
#define BLD_FEATURE_PMAKER 0
#define BLD_FEATURE_SSL 0
#define BLD_FEATURE_WINSDK 1
#define BLD_FEATURE_CC 1
#define BLD_FEATURE_LINK 1
#define BLD_FEATURE_DUMPBIN 1
#define BLD_FEATURE_RC 1
#define BLD_FEATURE_CGI 1
#define BLD_FEATURE_DIR 1
#define BLD_FEATURE_EJSCRIPT 0
#define BLD_FEATURE_ESP 1
#define BLD_FEATURE_OPENSSL 0
#define BLD_FEATURE_MATRIXSSL 0
#define BLD_FEATURE_SQLITE 1
#define BLD_FEATURE_UTEST 1
