/*
    bit.h -- Build It Configuration Header for linux-i686

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BLD_PRODUCT "appweb"
#define BLD_NAME "Embedthis Appweb"
#define BLD_COMPANY "Embedthis"
#define BLD_APPWEB_PRODUCT 1
#define BLD_VERSION "4.0.0"
#define BLD_NUMBER "B2"
#define BLD_MAJOR_VERSION 4
#define BLD_MINOR_VERSION 0
#define BLD_PATCH_VERSION 0
#define BLD_VNUM 400000000
#define BLD_CONFIG_CMD "bit -emulate linux-i686 -without all configure -gen sh,make"
#define BLD_LIB_NAME "bin"
#define BLD_CFG_PREFIX "/etc/appweb"
#define BLD_BIN_PREFIX "/usr/lib/appweb/4.0.0/bin"
#define BLD_DOC_PREFIX "/usr/lib/appweb/doc"
#define BLD_INC_PREFIX "/usr/lib/appweb/4.0.0/inc"
#define BLD_JEM_PREFIX "/usr/lib/appweb/jems"
#define BLD_LIB_PREFIX "/usr/lib/appweb/4.0.0/bin"
#define BLD_LOG_PREFIX "/var/log/appweb"
#define BLD_MAN_PREFIX "/usr/lib/appweb/man"
#define BLD_PRD_PREFIX "/usr/lib/appweb"
#define BLD_SAM_PREFIX "/usr/lib/appweb/samples"
#define BLD_SPL_PREFIX "/var/spool/appweb"
#define BLD_SRC_PREFIX "/usr/src/appweb-4.0.0"
#define BLD_VER_PREFIX "/usr/lib/appweb/4.0.0"
#define BLD_WEB_PREFIX "/var/www/appweb-default"
#define BLD_EXE ""
#define BLD_SHLIB ".so"
#define BLD_SHOBJ ".so"
#define BLD_LIB ".a"
#define BLD_OBJ ".o"
#define BLD_FEATURE_AUTH_FILE 1
#define BLD_FEATURE_AUTH_PAM 0
#define BLD_FEATURE_MDB 1
#define BLD_FEATURE_SDB 0
#define BLD_MANAGER "appman"
#define BLD_CC_DOUBLE_BRACES 0
#define BLD_CC_DYN_LOAD 1
#define BLD_CC_EDITLINE 0
#define BLD_CC_MMU 1
#define BLD_CC_MTUNE 1
#define BLD_CC_PAM 1
#define BLD_CC_STACK_PROTECTOR 1
#define BLD_CC_SYNC 1
#define BLD_CC_SYNC_CAS 1
#define BLD_CC_UNNAMED_UNIONS 1
#define BLD_CC_WARN_64TO32 0
#define BLD_CC_WARN_UNUSED 1
#define BLD_FEATURE_HTTP 0
#define BLD_FEATURE_DOXYGEN 0
#define BLD_FEATURE_DSI 0
#define BLD_FEATURE_EJS 0
#define BLD_FEATURE_MAN 0
#define BLD_FEATURE_MAN2HTML 0
#define BLD_FEATURE_PHP 0
#define BLD_FEATURE_PMAKER 0
#define BLD_FEATURE_SSL 0
#define BLD_FEATURE_CC 1
#define BLD_CC "gcc"
#define BLD_FEATURE_LINK 1
#define BLD_LINK "ld"
#define BLD_FEATURE_CGI 1
#define BLD_CGI "/Users/mob/git/appweb/src/modules/cgiHandler.c"
#define BLD_FEATURE_DIR 1
#define BLD_DIR "/Users/mob/git/appweb/src/dirHandler.c"
#define BLD_FEATURE_DPKG 0
#define BLD_FEATURE_ESP 1
#define BLD_ESP "/Users/mob/git/appweb/src/esp/espHandler.c"
#define BLD_FEATURE_OPENSSL 0
#define BLD_FEATURE_MATRIXSSL 0
#define BLD_FEATURE_SQLITE 1
#define BLD_SQLITE "/Users/mob/git/appweb/src/deps/sqlite"
#define BLD_FEATURE_EJSCRIPT 0
