/*
    bit.h -- Build It Configuration Header for solaris-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BIT_PRODUCT "appweb"
#define BIT_NAME "Embedthis Appweb"
#define BIT_COMPANY "Embedthis"
#define BIT_APPWEB_PRODUCT 1
#define BIT_VERSION "4.0.0"
#define BIT_NUMBER "0"
#define BIT_MAJOR_VERSION 4
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 400000000
#define BIT_CONFIG_CMD "bit -d -q -platform solaris-x86 -without all -configure . -gen sh,make"
#define BIT_PROFILE "debug"
#define BIT_CFG_PREFIX "/etc/appweb"
#define BIT_BIN_PREFIX "/usr/lib/appweb/4.0.0/bin"
#define BIT_INC_PREFIX "/usr/lib/appweb/4.0.0/inc"
#define BIT_LOG_PREFIX "/var/log/appweb"
#define BIT_PRD_PREFIX "/usr/lib/appweb"
#define BIT_SPL_PREFIX "/var/spool/appweb"
#define BIT_SRC_PREFIX "/usr/src/appweb-4.0.0"
#define BIT_VER_PREFIX "/usr/lib/appweb/4.0.0"
#define BIT_WEB_PREFIX "/var/www/appweb-default"
#define BIT_EXE ""
#define BIT_SHLIB ".so"
#define BIT_SHOBJ ".so"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"
#define BIT_FEATURE_MDB 1
#define BIT_FEATURE_SDB 0
#define BIT_MANAGER "appman"
#define BIT_CC_DOUBLE_BRACES 1
#define BIT_CC_DYN_LOAD 1
#define BIT_CC_EDITLINE 0
#define BIT_CC_MMU 1
#define BIT_CC_MTUNE 1
#define BIT_CC_PAM 0
#define BIT_CC_STACK_PROTECTOR 1
#define BIT_CC_SYNC 0
#define BIT_CC_SYNC_CAS 0
#define BIT_CC_UNNAMED_UNIONS 1
#define BIT_CC_WARN_64TO32 0
#define BIT_CC_WARN_UNUSED 0
#define BIT_FEATURE_HTTP 1
#define BIT_FEATURE_DOXYGEN 0
#define BIT_FEATURE_DSI 0
#define BIT_FEATURE_EJS 0
#define BIT_FEATURE_MAN 0
#define BIT_FEATURE_MAN2HTML 0
#define BIT_FEATURE_PHP 0
#define BIT_FEATURE_PMAKER 0
#define BIT_FEATURE_SSL 0
#define BIT_FEATURE_EJSCRIPT 0
#define BIT_FEATURE_MATRIXSSL 0
#define BIT_FEATURE_OPENSSL 0
#define BIT_FEATURE_CC 1
#define BIT_FEATURE_LINK 1
#define BIT_FEATURE_PCRE 1
#define BIT_FEATURE_CGI 1
#define BIT_FEATURE_DIR 1
#define BIT_FEATURE_ESP 1
#define BIT_FEATURE_SQLITE 1
#define BIT_FEATURE_UTEST 1
#define BIT_FEATURE_ZIP 1
