#
#	Makefile for the http modules
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

MAKE_IFLAGS		:= $(BLD_OPENSSL_IFLAGS) $(BLD_MATRIXSSL_IFLAGS)

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
