#
#	Makefile for the AppWeb C samples 
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

PRE_DIRS		+= simpleServer 
PRE_DIRS 		+= simpleClient 
PRE_DIRS 		+= simpleHandler

# 	MOB - need simpleEsp

ifeq ($(BLD_FEATURE_EJSCRIPT),1)
	PRE_DIRS 	+= simpleEjs
endif

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
