#!/bin/sh
#
# 	postinst -- Post installation script for appweb
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_LIB_PREFIX="!!ORIG_BLD_LIB_PREFIX!!"
BLD_LOG_PREFIX="!!ORIG_BLD_LOG_PREFIX!!"
BLD_SPL_PREFIX="!!ORIG_BLD_SPL_PREFIX!!"

###############################################################################

setPerms() {
	local g u

	for u in www-data _www nobody Administrator ; do
		grep "$u" /etc/passwd >/dev/null
		if [ $? = 0 ] ; then
			username=$u
			break
		fi
	done
	for g in www-data _www nobody nogroup Administrator ; do
		grep "$g" /etc/group >/dev/null
		if [ $? = 0 ] ; then
			groupname=$g
			break
		fi
	done
	if [ "$username" = "" -o "$groupname" = "" ] ; then
		echo "Can't find a suitable user/group for $BLD_PRODUCT" 1>&2
		exit 255
	fi
    mkdir -p "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
    chown $username "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
    chgrp $groupname "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
    chmod 755 "$BLD_SPL_PREFIX" "$BLD_SPL_PREFIX/cache" "$BLD_LOG_PREFIX"
}

###############################################################################
#
#	Main
#

cd /
action=$1

case $action in
	configure)							# when new
        setPerms
		oldVersion=$2
        appman -v install
        if [ "$APPWEB_DONT_START" != 1 ] ; then
            appman enable
            appman start
        fi
        echo
		echo "$BLD_NAME installation successful."
		;;
	abort-upgrade)						# when old
		;;
	abort-remove)
		# 	sometimes conflictor's-postinst abort-remove in-favor package new-version
		;;
esac
exit 0
