#!/bin/sh
#
# 	postinst -- Post installation script for appweb
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_LIB_PREFIX="!!ORIG_BLD_LIB_PREFIX!!"

###############################################################################

setup() {
	local g u

	#
	#	Select default username
	#
	for u in nobody www-data 
	do
		grep "$u" /etc/passwd >/dev/null
		if [ $? = 0 ] ; then
			username=$u
			break
		fi
	done

	if [ "$username" = "" ] ; then
		echo "Can't find a suitable username in /etc/passwd for $BLD_PRODUCT" 1>&2
		exit 255
	fi
	
	#
	#	Select default group name
	#
	for g in nobody nogroup www-data 
	do
		grep "$g" /etc/group >/dev/null
		if [ $? = 0 ] ; then
			groupname=$g
			break
		fi
	done
	
	if [ "$groupname" = "" ] ; then
		echo "Can't find a suitable group in /etc/group for $BLD_PRODUCT" 1>&2
		exit 255
	fi
}


###############################################################################
#
#	Main
#

cd /
action=$1

case $action in
	configure)							# when new
		oldVersion=$2
        appman -v install
        if [ "$APPWEB_DONT_START" != 1 ] ; then
            appman enable
            appman start
        fi
        echo
		echo "$BLD_NAME installation successful."
		;;
	abort-upgrade)						# when old
		;;
	abort-remove)
		# 	sometimes conflictor's-postinst abort-remove in-favor package new-version
		;;
esac
exit 0
