#!/bin/sh
#
# 	preinst -- Pre install script for appweb
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_CFG_PREFIX=!!ORIG_BLD_CFG_PREFIX!!

#
#	Modify service. Usage:configureService stop|remove
#
configureService() {
	local action=$1

	case $action in
	stop)
        if [ -x /usr/local/bin/appman ] ; then
            appman stop >/dev/null 2>&1 ; true
        fi
        #   Keep this for earlier versions without appman
		if [ -f /etc/rc.d/init.d/$BLD_PRODUCT ] ; then
			if which service >/dev/null 2>&1 ; then
				service $BLD_PRODUCT $action
			elif which invoke-rc.d >/dev/null 2>&1  ; then
				invoke-rc.d $BLD_PRODUCT $action || true
			fi
        elif [ -f /etc/init.d/$BLD_PRODUCT ] ; then
            /etc/init.d/$BLD_PRODUCT stop >/dev/null 2>&1
		fi
		if [ "`/bin/pidof !!ORIG_BLD_BIN_PREFIX!!/$BLD_PRODUCT`" != "" ] ; then
            kill -9 `/bin/pidof !!ORIG_BLD_BIN_PREFIX!!/$BLD_PRODUCT`
        fi
		rm -rf /var/lock/subsys/$BLD_PRODUCT /var/lock/$BLD_PRODUCT /var/log/$BLD_PRODUCT /var/run/$BLD_PRODUCT
		;;

	remove)
        if [ -x /usr/local/bin/appman ] ; then
            appman uninstall
        fi
        #   Keep this for earlier versions without appman
		if which chkconfig >/dev/null 2>&1 ; then
			chkconfig --del $BLD_PRODUCT
			rm /etc/rc.d/init.d/$BLD_PRODUCT
		elif which update-rc.d >/dev/null 2>&1 ; then
			rm -f /etc/init.d/$BLD_PRODUCT
			update-rc.d $BLD_PRODUCT remove >/dev/null || true
        elif [ -f /etc/init.d/$BLD_PRODUCT ] ; then
            ( cd /etc/init.d ; /etc/init.d/$BLD_PRODUCT disable )
		fi
		;;
	esac
}

###############################################################################
#
#	Main
#
cd /
action=$1

case $action in
	remove|install)					# when new
		# or conflictor's prerm remove in-favor package new-version
		oldVersion=$2
		configureService stop
		configureService remove
		;;
	upgrade)				# when old
		newVersion=$2
		configureService stop
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	deconfigure)			# when old
		# 	deconfigure in-favor package-being-installed version removing 
		#	conflicting-package version
esac
exit 0
