#!/bin/sh
#
# 	prerm -- Pre removal script for appweb
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_CFG_PREFIX=!!ORIG_BLD_CFG_PREFIX!!

###############################################################################
#
#	Main
#
cd /
action=$1
case $action in
	remove)					# when new
		# or conflictor's prerm remove in-favor package new-version
		oldVersion=$2
		appman stop >/dev/null 2>&1 ; true
		appman disable >/dev/null 2>&1 ; true
		appman uninstall >/dev/null 2>&1 ; true
		pid=`/bin/pidof !!ORIG_BLD_BIN_PREFIX!!/$BLD_PRODUCT; true`
		[ "$pid" != "" ] && kill -9 $pid
		rm -rf /var/lock/subsys/$BLD_PRODUCT /var/lock/$BLD_PRODUCT /var/log/$BLD_PRODUCT /var/run/$BLD_PRODUCT
		;;
	upgrade)				# when old
		newVersion=$2
		appman uninstall
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	deconfigure)			# when old
		# 	deconfigure in-favor package-being-installed version removing 
		#	conflicting-package version
esac
exit 0
