.TH APPWEBMONITOR "1" "March 2012" "appwebMonitor" "User Commands"
.SH NAME
appwebMonitor - Appweb Monitor Program for Windows
.SH SYNOPSIS
.B appwebMonitor
[\fI--manage\fR] 
[\fI--stop\fR] 
.SH DESCRIPTION
The appwebMonitor program runs in the Windows tray and provides visual feedback and control over the Appweb and Appweb 
manager process. Right-click to display the Monitor menu. From this menu, you can start or stop Appweb and launch
the management console. Double-click will launch a browser homed to the web server home page.
.SH OPTIONS
.TP
\fB\--manage\fR
Launch a browser to display the Appweb management console. This is currently not implemented.
.TP
\fB\--stop\fR
Stop the currently executing Monitor program.
.SH "REPORTING BUGS"
Report bugs to <dev@embedthis.com>.
.SH COPYRIGHT
Copyright \(co 2003-2012 Embedthis Software.
.br
.SH "SEE ALSO"
appweb
