.TH AUTH "1" "February 2011" "auth" "User Commands"
.SH NAME
auth \- Create and manage passwords
.SH SYNOPSIS
.B auth [\fI-c\fR]
[\fI-p password\fR] 
passwordFile realm userName
.SH OPTIONS
.TP
\fB\-p password\fR 
Specifies a password to use to for the user.
.TP
\fB\-c\fR 
Create the specified password file
.PP
.SH DESCRIPTION
The auth program is used to create user passwords in a nominated password file. Unlike Apache, 
Appweb uses the same authorization file andeformat for Digest and Basic authentication. This simplifies administration.
.SH "REPORTING BUGS"
Report bugs to <dev@embedthis.com>.
.SH COPYRIGHT
Copyright \(co 2003-2011 Embedthis Software.
.br
.SH "SEE ALSO"
