.TH HTTPPASSWORD "1" "February 2010" "httpPassword" "User Commands"
.SH NAME
httpPassword \- Create and manage passwords
.SH SYNOPSIS
.B httpComp [\fI-c\fR]
[\fI-p password\fR] 
passwordFile realm userName
.SH OPTIONS
.TP
\fB\-p password\fR 
Specifies a password to use to for the user.
.TP
\fB\-c\fR 
Create the specified password file
.PP
.SH DESCRIPTION
The httpPassword program is used to create user passwords in a nominated
password file. Unlike Apache, Appweb uses the same authorization file and
format for Digest and Basic authentication. This simplifies administration.
.SH "REPORTING BUGS"
Report bugs to <dev@embedthis.com>.
.SH COPYRIGHT
Copyright \(co 2003-2010 Embedthis Software.
.br
.SH "SEE ALSO"
