#
#	Makefile for the AppWeb C++ samples 
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 		.makedep

PRE_DIRS 		+= simpleHandler
PRE_DIRS 		+= simpleModule

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
