#
#	Makefile for the Appweb samples
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#
#	This makefile is for use on development systems only and is not part of the released product.
# 

include 		.makedep 

ifeq ($(BLD_FEATURE_SAMPLES),1)
	PRE_DIRS	+= c ejs
endif
