#!/bin/bash
#
#	postflight -- Post flight script for documentation
#
#	Copyright (c) Embedthis Software LLC, 2003-2010. All Rights Reserved.
#
###############################################################################

PKG_DIR="$1"
INS_DIR="$2"
BIN="!!ORIG_BLD_BIN_PREFIX!!"
NAME="!!ORIG_BLD_DOC_PREFIX!!"
path="${INS_DIR}${NAME}"

${BIN}/linkup Install

if [ -z "$COMMAND_LINE_INSTALL" ] ; then
    port=`cat !!ORIG_BLD_CFG_PREFIX!!/appweb.conf | grep Listen | awk '{print $2 }'`
    sleep 5 
    open "http://127.0.0.1:${port}/index.html"
fi

exit 0
