#
#	Makefile for the Appweb samples
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#
#	This makefile is for use on development systems only and is not part of the released product.
# 

include 		.makedep 

PRE_DIRS		+= c

ifneq	($(BLD_OS,VXWORKS),)
	PRE_DIRS	+= c++
endif

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
