#
#	Makefile for the Appweb samples
#
#	Copyright (c) Embedthis Software LLC, 2003-2012. All Rights Reserved.
#

include 		.makedep 

ifeq	($(BUILDING_TARGET),1)
	PRE_DIRS		+= c

	ifneq	($(BLD_OS,VXWORKS),)
		PRE_DIRS	+= c++
	endif
endif

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
