#
#	Makefile for Windows Visual Studio projects
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

PRE_DIRS	= appweb-static appweb-dynamic

include     .makedep

cleanExtra:
	echo rm -fr appweb*/Win32 appweb/*Pocket* 
	rm -fr appweb*/Win32 appweb*/*Pocket* 

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4 noexpandtab
#
