#!/bin/bash

for w in appweb
do
	for f in \
		/etc/$w \
		/usr/bin/${w}* \
		/usr/bin/http \
		/usr/bin/httprom \
		/usr/bin/httpPassword \
		/var/lib/$w \
		/usr/lib/lib${w}* \
		/usr/share/${w} \
		/usr/share/doc/${w} \
		/usr/share/man/${w} \
		/usr/share/man/man1/${w}*  \
		/usr/share/man/man1/httpClient* \
		/usr/share/man/man1/httpComp* \
		/usr/share/man/man1/httpPassword* \
        /usr/share/man/man1/ec.1.gz \
        /usr/share/man/man1/ejs.1.gz \
        /usr/share/man/man1/ejsmod.1.gz \
        /usr/share/man/man1/ejsvm.1.gz \
        /usr/share/man/man1/http.1.gz \
		/usr/include/${w}* \
		/var/www/${w}* \
		/var/log/${w}* \
		/usr/src/${w}* 
	do
		if [ -f $f -o -d $f ] ; then
			echo -e "\n=====  $f =====\n"
			ls $f
		fi
	done
done
